/*
 * IntroToAlphas.java
 *
 * Created on September 24, 2008, 2:54 PM
 */

package org.netbeans.learn1;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author  Preeti
 */
public class IntroToAlphas extends javax.swing.JFrame {

    /** Creates new form IntroToAlphas */
    public IntroToAlphas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        speech = new javax.swing.JButton();
        back = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        AWord = new javax.swing.JButton();
        BWord = new javax.swing.JButton();
        CWord = new javax.swing.JButton();
        DWord = new javax.swing.JButton();
        EWord = new javax.swing.JButton();
        FWord = new javax.swing.JButton();
        GWord = new javax.swing.JButton();
        IWord = new javax.swing.JButton();
        HWord = new javax.swing.JButton();
        KWord = new javax.swing.JButton();
        LWord = new javax.swing.JButton();
        JWord = new javax.swing.JButton();
        MWord = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        NWord = new javax.swing.JButton();
        OWord = new javax.swing.JButton();
        PWord = new javax.swing.JButton();
        QWord = new javax.swing.JButton();
        RWord = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        letterlabel = new javax.swing.JLabel();
        wordlabel = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        speech.setBackground(new java.awt.Color(51, 51, 51));
        speech.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        speech.setForeground(new java.awt.Color(0, 0, 255));
        speech.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_BACK")); // NOI18N
        speech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speechActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(0, 0, 0));
        back.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        back.setForeground(new java.awt.Color(0, 0, 255));
        back.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_SPEECH")); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0, 0, 0));
        exit.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        exit.setForeground(new java.awt.Color(0, 0, 204));
        exit.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_EXIT")); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "IntroToAlphas.jLabel1.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "LABEL_CLICK_ALPHABET")); // NOI18N

        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        AWord.setBackground(new java.awt.Color(102, 255, 0));
        AWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        AWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_A")); // NOI18N
        AWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AWordActionPerformed(evt);
            }
        });

        BWord.setBackground(new java.awt.Color(102, 255, 0));
        BWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        BWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_B")); // NOI18N
        BWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BWordActionPerformed(evt);
            }
        });

        CWord.setBackground(new java.awt.Color(153, 255, 0));
        CWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        CWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_C")); // NOI18N
        CWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CWordActionPerformed(evt);
            }
        });

        DWord.setBackground(new java.awt.Color(102, 255, 0));
        DWord.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        DWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_D")); // NOI18N
        DWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DWordActionPerformed(evt);
            }
        });

        EWord.setBackground(new java.awt.Color(153, 255, 0));
        EWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        EWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_E")); // NOI18N
        EWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EWordActionPerformed(evt);
            }
        });

        FWord.setBackground(new java.awt.Color(153, 255, 0));
        FWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        FWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_F")); // NOI18N
        FWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FWordActionPerformed(evt);
            }
        });

        GWord.setBackground(new java.awt.Color(153, 255, 0));
        GWord.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        GWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_G")); // NOI18N
        GWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GWordActionPerformed(evt);
            }
        });

        IWord.setBackground(new java.awt.Color(153, 255, 51));
        IWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        IWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_I")); // NOI18N
        IWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IWordActionPerformed(evt);
            }
        });

        HWord.setBackground(new java.awt.Color(153, 255, 0));
        HWord.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        HWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_H")); // NOI18N
        HWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HWordActionPerformed(evt);
            }
        });

        KWord.setBackground(new java.awt.Color(153, 255, 51));
        KWord.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        KWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_K")); // NOI18N
        KWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KWordActionPerformed(evt);
            }
        });

        LWord.setBackground(new java.awt.Color(153, 255, 0));
        LWord.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        LWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_L")); // NOI18N
        LWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LWordActionPerformed(evt);
            }
        });

        JWord.setBackground(new java.awt.Color(153, 255, 0));
        JWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        JWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_J")); // NOI18N
        JWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JWordActionPerformed(evt);
            }
        });

        MWord.setBackground(new java.awt.Color(153, 255, 0));
        MWord.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        MWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_M")); // NOI18N
        MWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(AWord, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(BWord, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CWord, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DWord, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EWord, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FWord, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GWord, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HWord, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IWord, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JWord, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KWord, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LWord, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MWord, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1663, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(AWord, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addComponent(BWord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(CWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(GWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(HWord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(IWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(JWord, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(KWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(LWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(MWord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(FWord, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(EWord, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(DWord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        NWord.setBackground(new java.awt.Color(153, 255, 51));
        NWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        NWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_N")); // NOI18N

        OWord.setBackground(new java.awt.Color(153, 255, 51));
        OWord.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        OWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_O")); // NOI18N
        OWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OWordActionPerformed(evt);
            }
        });

        PWord.setBackground(new java.awt.Color(102, 255, 51));
        PWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        PWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_P")); // NOI18N
        PWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PWordActionPerformed(evt);
            }
        });

        QWord.setBackground(new java.awt.Color(153, 255, 51));
        QWord.setFont(new java.awt.Font("Arial Narrow", 1, 12)); // NOI18N
        QWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_Q")); // NOI18N
        QWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QWordActionPerformed(evt);
            }
        });

        RWord.setBackground(new java.awt.Color(153, 255, 51));
        RWord.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        RWord.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_R")); // NOI18N
        RWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RWordActionPerformed(evt);
            }
        });

        S.setBackground(new java.awt.Color(102, 255, 51));
        S.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        S.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_S")); // NOI18N
        S.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SActionPerformed(evt);
            }
        });

        T.setBackground(new java.awt.Color(102, 255, 51));
        T.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        T.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_T")); // NOI18N
        T.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TActionPerformed(evt);
            }
        });

        U.setBackground(new java.awt.Color(102, 255, 51));
        U.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        U.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_U")); // NOI18N
        U.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UActionPerformed(evt);
            }
        });

        V.setBackground(new java.awt.Color(102, 255, 0));
        V.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        V.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_V")); // NOI18N
        V.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VActionPerformed(evt);
            }
        });

        W.setBackground(new java.awt.Color(102, 255, 51));
        W.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        W.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_W")); // NOI18N
        W.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WActionPerformed(evt);
            }
        });

        X.setBackground(new java.awt.Color(102, 255, 51));
        X.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        X.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_X")); // NOI18N
        X.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XActionPerformed(evt);
            }
        });

        Y.setBackground(new java.awt.Color(153, 255, 51));
        Y.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 12)); // NOI18N
        Y.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_Y")); // NOI18N
        Y.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                YActionPerformed(evt);
            }
        });

        Z.setBackground(new java.awt.Color(102, 255, 51));
        Z.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14)); // NOI18N
        Z.setText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "BUTTON_Z")); // NOI18N
        Z.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(NWord, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OWord, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PWord, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QWord, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RWord, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(W)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Y, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Z, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1658, 1658, 1658))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(QWord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(RWord, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(S, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(U, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(X, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Y, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(Z, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                        .addComponent(W, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(V, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(NWord, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(OWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PWord, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        letterlabel.setBackground(new java.awt.Color(255, 255, 255));
        letterlabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24));
        letterlabel.setForeground(new java.awt.Color(255, 102, 0));
        letterlabel.setToolTipText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "IntroToAlphas.letterlabel.toolTipText")); // NOI18N
        letterlabel.setAlignmentY(0.0F);
        letterlabel.setBorder(new javax.swing.border.MatteBorder(null));
        letterlabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        letterlabel.setOpaque(true);

        wordlabel.setBackground(new java.awt.Color(255, 255, 0));
        wordlabel.setFont(new java.awt.Font("Arial Unicode MS", 1, 48));
        wordlabel.setForeground(new java.awt.Color(255, 0, 51));
        wordlabel.setToolTipText(org.openide.util.NbBundle.getMessage(IntroToAlphas.class, "IntroToAlphas.wordlabel.toolTipText")); // NOI18N
        wordlabel.setBorder(new javax.swing.border.MatteBorder(null));
        wordlabel.setOpaque(true);

        imagelabel.setBackground(new java.awt.Color(255, 255, 255));
        imagelabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagelabel.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(wordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(letterlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(letterlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(wordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1669, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(267, 267, 267)
                        .addComponent(speech)
                        .addGap(18, 18, 18)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speech)
                    .addComponent(back)
                    .addComponent(exit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void speechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speechActionPerformed
/*String inputString=wordlabel.getText();
String[] words=inputString.split("");
for(String word : words)
{
    if(word.equals("Apple"))
    {
        try{
            AudioStream wow=new AudioStream(new FileInputStream(new File("Apple.wow")));
            AudioPlayer.player.start(wow);
        }
        catch(Exception ex)
        {
            ex.printStackTrace();
        }
    }
    try {
		        long numMillisecondsToSleep = 1000; // 5 seconds
		        Thread.sleep(numMillisecondsToSleep);
		    } catch (InterruptedException e) {
    }
	
}*/
    
    // TODO add your handling code here:
}//GEN-LAST:event_speechActionPerformed

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
setVisible(false);
    new Learning().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_backActionPerformed

private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);
    // TODO add your handling code here:
}//GEN-LAST:event_exitActionPerformed

private void AWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AWordActionPerformed
ImageIcon ic1=new ImageIcon("D:\\Ash\\PROJECT\\images\\Apple.jpeg");
 ImageIcon ic2=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\A.jpeg");
wordlabel.setText("         Apple   ");
 Image image1=ic1.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image2=ic2.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon1=new ImageIcon(image1);
 ImageIcon icon2=new ImageIcon(image2);
 imagelabel.setIcon(icon1);
 letterlabel.setIcon(icon2);
 
 
 
 
    // TODO add your handling code here:
}//GEN-LAST:event_AWordActionPerformed

private void BWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BWordActionPerformed
ImageIcon ic3=new ImageIcon("D:\\Ash\\PROJECT\\images\\ball.jpeg");
 ImageIcon ic4=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\B.jpeg");
 wordlabel.setText("         Ball   ");
 Image image3=ic3.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image4=ic4.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon3=new ImageIcon(image3);
 ImageIcon icon4=new ImageIcon(image4);
 imagelabel.setIcon(icon3);
 letterlabel.setIcon(icon4);
 
    // TODO add your handling code here:
}//GEN-LAST:event_BWordActionPerformed

private void CWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CWordActionPerformed
ImageIcon ic5=new ImageIcon("D:\\Ash\\PROJECT\\images\\cat.jpeg");
 ImageIcon ic6=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\c.jpeg");
 wordlabel.setText("         Cat   ");
 Image image5=ic5.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image6=ic6.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon5=new ImageIcon(image5);
 ImageIcon icon6=new ImageIcon(image6);
 imagelabel.setIcon(icon5);
 letterlabel.setIcon(icon6);
    // TODO add your handling code here:
}//GEN-LAST:event_CWordActionPerformed

private void DWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DWordActionPerformed
ImageIcon ic7=new ImageIcon("D:\\Ash\\PROJECT\\images\\Doll2.jpeg");
 ImageIcon ic8=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\d.jpeg");
 wordlabel.setText("        Doll   ");
 Image image7=ic7.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image8=ic8.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon7=new ImageIcon(image7);
 ImageIcon icon8=new ImageIcon(image8);
 imagelabel.setIcon(icon7);
 letterlabel.setIcon(icon8);
    // TODO add your handling code here:
}//GEN-LAST:event_DWordActionPerformed

private void EWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EWordActionPerformed
ImageIcon ic9=new ImageIcon("D:\\Ash\\PROJECT\\images\\elephant.jpeg");
ImageIcon ic10=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\E.jpeg");
wordlabel.setText("Egg");
Image image9=ic9.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image10=ic10.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon9=new ImageIcon(image9);
ImageIcon icon10=new ImageIcon(image10);
imagelabel.setIcon(icon9);
letterlabel.setIcon(icon10);

    // TODO add your handling code here:
}//GEN-LAST:event_EWordActionPerformed

private void FWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FWordActionPerformed
ImageIcon ic11=new ImageIcon("D:\\Ash\\PROJECT\\images\\frog.jpeg");
 ImageIcon ic12=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\F.jpeg");
 wordlabel.setText("        Frog   ");
 Image image11=ic11.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image12=ic12.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon11=new ImageIcon(image11);
 ImageIcon icon12=new ImageIcon(image12);
 imagelabel.setIcon(icon11);
 letterlabel.setIcon(icon12);
    // TODO add your handling code here:
}//GEN-LAST:event_FWordActionPerformed

private void GWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GWordActionPerformed
ImageIcon ic13=new ImageIcon("D:\\Ash\\PROJECT\\images\\goat.jpeg");
 ImageIcon ic14=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\G.jpeg");
wordlabel.setText("         GOAT   ");
 Image image13=ic13.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image14=ic14.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon13=new ImageIcon(image13);
 ImageIcon icon14=new ImageIcon(image14);
 imagelabel.setIcon(icon13);
 letterlabel.setIcon(icon14);
    // TODO add your handling code here:
}//GEN-LAST:event_GWordActionPerformed

private void IWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IWordActionPerformed
ImageIcon ic17=new ImageIcon("D:\\Ash\\PROJECT\\images\\Ice-cream.jpeg");
 ImageIcon ic18=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\I.jpeg");
wordlabel.setText("         ICE-Cream   ");
 Image image17=ic17.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image18=ic18.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon17=new ImageIcon(image17);
 ImageIcon icon18=new ImageIcon(image18);
 imagelabel.setIcon(icon17);
 letterlabel.setIcon(icon18);
    // TODO add your handling code here:
}//GEN-LAST:event_IWordActionPerformed

private void HWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HWordActionPerformed
ImageIcon ic15=new ImageIcon("D:\\Ash\\PROJECT\\images\\hammer.jpeg");
 ImageIcon ic16=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\H.jpeg");
wordlabel.setText("         Hammer   ");
 Image image15=ic15.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image16=ic16.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon15=new ImageIcon(image15);
 ImageIcon icon16=new ImageIcon(image16);
 imagelabel.setIcon(icon15);
 letterlabel.setIcon(icon16);
    // TODO add your handling code here:
}//GEN-LAST:event_HWordActionPerformed

private void KWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KWordActionPerformed
ImageIcon ic21=new ImageIcon("D:\\Ash\\PROJECT\\images\\Kitten1.jpeg");
 ImageIcon ic22=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\K.jpeg");
wordlabel.setText("         Kitten   ");
 Image image21=ic21.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image22=ic22.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon21=new ImageIcon(image21);
 ImageIcon icon22=new ImageIcon(image22);
 imagelabel.setIcon(icon21);
 letterlabel.setIcon(icon22);
    // TODO add your handling code here:
}//GEN-LAST:event_KWordActionPerformed

private void LWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LWordActionPerformed
ImageIcon ic23=new ImageIcon("D:\\Ash\\PROJECT\\images\\lion.jpeg");
 ImageIcon ic24=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\L.jpeg");
wordlabel.setText("         Lion   ");
 Image image23=ic23.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image24=ic24.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon23=new ImageIcon(image23);
 ImageIcon icon24=new ImageIcon(image24);
 imagelabel.setIcon(icon23);
 letterlabel.setIcon(icon24);
    // TODO add your handling code here:
}//GEN-LAST:event_LWordActionPerformed

private void JWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JWordActionPerformed
ImageIcon ic19=new ImageIcon("D:\\Ash\\PROJECT\\images\\jerry.jpeg");
 ImageIcon ic20=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\J.jpeg");
wordlabel.setText("     Jerry       ");
 Image image19=ic19.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image20=ic20.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon19=new ImageIcon(image19);
 ImageIcon icon20=new ImageIcon(image20);
 imagelabel.setIcon(icon19);
 letterlabel.setIcon(icon20);
    // TODO add your handling code here:
}//GEN-LAST:event_JWordActionPerformed

private void MWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MWordActionPerformed
ImageIcon ic25=new ImageIcon("D:\\Ash\\PROJECT\\images\\mickey mouse.jpeg");
 ImageIcon ic26=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\M.jpeg");
wordlabel.setText("   Mickey Mouse   ");
 Image image25=ic25.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image26=ic26.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon25=new ImageIcon(image25);
 ImageIcon icon26=new ImageIcon(image26);
 imagelabel.setIcon(icon25);
 letterlabel.setIcon(icon26);
    // TODO add your handling code here:
}//GEN-LAST:event_MWordActionPerformed

private void OWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OWordActionPerformed
ImageIcon ic29=new ImageIcon("D:\\Ash\\PROJECT\\images\\owl.jpeg");
 ImageIcon ic30=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\O.jpeg");
wordlabel.setText("         Kitten   ");
 Image image29=ic29.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image30=ic30.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon29=new ImageIcon(image29);
 ImageIcon icon30=new ImageIcon(image30);
 imagelabel.setIcon(icon29);
 letterlabel.setIcon(icon30);// TODO add your handling code here:
}//GEN-LAST:event_OWordActionPerformed

private void PWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PWordActionPerformed
ImageIcon ic31=new ImageIcon("D:\\Ash\\PROJECT\\images\\parrot.jpeg");
 ImageIcon ic32=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\P.jpeg");
wordlabel.setText("         Parrot   ");
 Image image31=ic31.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image32=ic32.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon31=new ImageIcon(image31);
 ImageIcon icon32=new ImageIcon(image32);
 imagelabel.setIcon(icon31);
 letterlabel.setIcon(icon32);// TODO add your handling code here:
}//GEN-LAST:event_PWordActionPerformed

private void QWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QWordActionPerformed
ImageIcon ic33=new ImageIcon("D:\\Ash\\PROJECT\\images\\queen.jpeg");
 ImageIcon ic34=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\Q.jpeg");
wordlabel.setText("         Queen   ");
 Image image33=ic33.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image34=ic34.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon33=new ImageIcon(image33);
 ImageIcon icon34=new ImageIcon(image34);
 imagelabel.setIcon(icon33);
 letterlabel.setIcon(icon34);
    // TODO add your handling code here:
}//GEN-LAST:event_QWordActionPerformed

private void RWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RWordActionPerformed
ImageIcon ic35=new ImageIcon("D:\\Ash\\PROJECT\\images\\Rose.jpeg");
 ImageIcon ic36=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\R.jpeg");
wordlabel.setText("         Rose   ");
 Image image35=ic35.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image36=ic36.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon35=new ImageIcon(image35);
 ImageIcon icon36=new ImageIcon(image36);
 imagelabel.setIcon(icon35);
 letterlabel.setIcon(icon36);
    // TODO add your handling code here:
}//GEN-LAST:event_RWordActionPerformed

private void SActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SActionPerformed
ImageIcon ic51=new ImageIcon("D:\\Ash\\PROJECT\\images\\sun.jpeg");
 ImageIcon ic52=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\S.jpeg");
wordlabel.setText("         Sun   ");
 Image image51=ic51.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image52=ic52.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon51=new ImageIcon(image51);
 ImageIcon icon52=new ImageIcon(image52);
 imagelabel.setIcon(icon51);
 letterlabel.setIcon(icon52);
    // TODO add your handling code here:
}//GEN-LAST:event_SActionPerformed

private void TActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TActionPerformed
ImageIcon ic37=new ImageIcon("D:\\Ash\\PROJECT\\images\\tiger.jpeg");
 ImageIcon ic38=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\T.jpeg");
wordlabel.setText("         Tiger   ");
 Image image37=ic37.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image38=ic38.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon37=new ImageIcon(image37);
 ImageIcon icon38=new ImageIcon(image38);
 imagelabel.setIcon(icon37);
 letterlabel.setIcon(icon38);
    // TODO add your handling code here:
}//GEN-LAST:event_TActionPerformed

private void UActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UActionPerformed
ImageIcon ic37=new ImageIcon("D:\\Ash\\PROJECT\\images\\umbrella.jpeg");
 ImageIcon ic38=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\U.jpeg");
wordlabel.setText("         Umbrella   ");
 Image image37=ic37.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image38=ic38.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon37=new ImageIcon(image37);
 ImageIcon icon38=new ImageIcon(image38);
 imagelabel.setIcon(icon37);
 letterlabel.setIcon(icon38);
    // TODO add your handling code here:
}//GEN-LAST:event_UActionPerformed

private void VActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VActionPerformed
ImageIcon ic53=new ImageIcon("D:\\Ash\\PROJECT\\images\\vehicle.jpeg");
 ImageIcon ic54=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\V.jpeg");
wordlabel.setText("         Vehicle   ");
 Image image53=ic53.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image54=ic54.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon53=new ImageIcon(image53);
 ImageIcon icon54=new ImageIcon(image54);
 imagelabel.setIcon(icon53);
 letterlabel.setIcon(icon54);
    // TODO add your handling code here:
}//GEN-LAST:event_VActionPerformed

private void WActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WActionPerformed
ImageIcon ic49=new ImageIcon("D:\\Ash\\PROJECT\\images\\well.jpeg");
 ImageIcon ic50=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\W.jpeg");
 wordlabel.setText("         Well   ");
 Image image49=ic49.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image50=ic50.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon49=new ImageIcon(image49);
 ImageIcon icon50=new ImageIcon(image50);
 imagelabel.setIcon(icon49);
 letterlabel.setIcon(icon50);
    // TODO add your handling code here:
}//GEN-LAST:event_WActionPerformed

private void XActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XActionPerformed
ImageIcon ic43=new ImageIcon("D:\\Ash\\PROJECT\\images\\x-ray.jpeg");
 ImageIcon ic44=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\X.jpeg");
wordlabel.setText("         X-Ray   ");
 Image image43=ic43.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image44=ic44.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon43=new ImageIcon(image43);
 ImageIcon icon44=new ImageIcon(image44);
 imagelabel.setIcon(icon43);
 letterlabel.setIcon(icon44);
    // TODO add your handling code here:
}//GEN-LAST:event_XActionPerformed

private void YActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_YActionPerformed
ImageIcon ic45=new ImageIcon("D:\\Ash\\PROJECT\\images\\yak.jpeg");
 ImageIcon ic46=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\Y.jpeg");
wordlabel.setText("         Yak   ");
 Image image45=ic45.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image46=ic46.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon45=new ImageIcon(image45);
 ImageIcon icon46=new ImageIcon(image46);
 imagelabel.setIcon(icon45);
 letterlabel.setIcon(icon46);
    // TODO add your handling code here:
}//GEN-LAST:event_YActionPerformed

private void ZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZActionPerformed
ImageIcon ic47=new ImageIcon("D:\\Ash\\PROJECT\\images\\zebra.jpeg");
 ImageIcon ic48=new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\Z.jpeg");
wordlabel.setText("         Zebra   ");
 Image image47=ic47.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 Image image48=ic48.getImage().getScaledInstance(letterlabel.getWidth(),letterlabel.getHeight(),Image.SCALE_AREA_AVERAGING);
 ImageIcon icon47=new ImageIcon(image47);
 ImageIcon icon48=new ImageIcon(image48);
 imagelabel.setIcon(icon47);
 letterlabel.setIcon(icon48);
    // TODO add your handling code here:
}//GEN-LAST:event_ZActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroToAlphas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AWord;
    private javax.swing.JButton BWord;
    private javax.swing.JButton CWord;
    private javax.swing.JButton DWord;
    private javax.swing.JButton EWord;
    private javax.swing.JButton FWord;
    private javax.swing.JButton GWord;
    private javax.swing.JButton HWord;
    private javax.swing.JButton IWord;
    private javax.swing.JButton JWord;
    private javax.swing.JButton KWord;
    private javax.swing.JButton LWord;
    private javax.swing.JButton MWord;
    private javax.swing.JButton NWord;
    private javax.swing.JButton OWord;
    private javax.swing.JButton PWord;
    private javax.swing.JButton QWord;
    private javax.swing.JButton RWord;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JButton back;
    private javax.swing.JButton exit;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel letterlabel;
    private javax.swing.JButton speech;
    private javax.swing.JLabel wordlabel;
    // End of variables declaration//GEN-END:variables

}
