/*
 * Learning.java
 *
 * Created on September 24, 2008, 2:46 PM
 */

package org.netbeans.learn1;

/**
 *
 * @author  Preeti
 */
public class Learning extends javax.swing.JFrame {

    /** Creates new form Learning */
    public Learning() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        introalpha = new javax.swing.JRadioButton();
        fillblanksalpha = new javax.swing.JRadioButton();
        fillblanksword = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        intronum = new javax.swing.JRadioButton();
        fillblanksnum = new javax.swing.JRadioButton();
        startbutton = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText(org.openide.util.NbBundle.getMessage(Learning.class, "LABEL_WELCOME")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText(org.openide.util.NbBundle.getMessage(Learning.class, "LABEL_START_learning")); // NOI18N

        introalpha.setFont(new java.awt.Font("Tahoma", 3, 14));
        introalpha.setForeground(new java.awt.Color(255, 0, 0));
        introalpha.setText(org.openide.util.NbBundle.getMessage(Learning.class, "OPTION_BUTTON_ALPHABET")); // NOI18N

        fillblanksalpha.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fillblanksalpha.setForeground(new java.awt.Color(255, 0, 0));
        fillblanksalpha.setText(org.openide.util.NbBundle.getMessage(Learning.class, "OPTION_BUTTON_ALPHA")); // NOI18N

        fillblanksword.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fillblanksword.setForeground(new java.awt.Color(255, 0, 0));
        fillblanksword.setText(org.openide.util.NbBundle.getMessage(Learning.class, "OPTION_BUTTON_WORD")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText(org.openide.util.NbBundle.getMessage(Learning.class, "LABEL_ALPHABET")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText(org.openide.util.NbBundle.getMessage(Learning.class, "LABEL_NUMBERS")); // NOI18N

        intronum.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        intronum.setForeground(new java.awt.Color(255, 0, 0));
        intronum.setText(org.openide.util.NbBundle.getMessage(Learning.class, "LABEL_INTRO")); // NOI18N

        fillblanksnum.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        fillblanksnum.setForeground(new java.awt.Color(255, 0, 0));
        fillblanksnum.setText(org.openide.util.NbBundle.getMessage(Learning.class, "LABEL_NUM")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(introalpha)
                            .addComponent(fillblanksalpha)
                            .addComponent(fillblanksword)
                            .addComponent(intronum)
                            .addComponent(fillblanksnum)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel4)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(introalpha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillblanksalpha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillblanksword)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addComponent(intronum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fillblanksnum)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        startbutton.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 18));
        startbutton.setText(org.openide.util.NbBundle.getMessage(Learning.class, "Learning.startbutton.text")); // NOI18N
        startbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbuttonActionPerformed(evt);
            }
        });

        exit.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        exit.setText(org.openide.util.NbBundle.getMessage(Learning.class, "BUTTON_EXIT")); // NOI18N
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(168, 168, 168))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(startbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(453, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(486, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(302, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(startbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(exit))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void startbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbuttonActionPerformed
if(introalpha.isSelected())
    {
        setVisible(false);
        new IntroToAlphas().setVisible(true);
    }
    if(fillblanksalpha.isSelected())
    {
        setVisible(false);
        new FillAlpha().setVisible(true);
    }
    /*if(fillblanksword.isSelected())
    {
        setVisible(false);
        new FillAlphaInWord().setVisible(true);
    }*/
    if(intronum.isSelected())
    {
        setVisible(false);
        new IntroToNum().setVisible(true);
    }
    if(fillblanksnum.isSelected())
    {
        setVisible(false);
        new FillNumber().setVisible(true);
    }
    
        // TODO add your handling code here:
}//GEN-LAST:event_startbuttonActionPerformed

private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
//setVisible(false);
//new ThankYou().setVisible(true);
System.exit(0);
// TODO add your handling code here:
}//GEN-LAST:event_exitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Learning().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton fillblanksalpha;
    private javax.swing.JRadioButton fillblanksnum;
    private javax.swing.JRadioButton fillblanksword;
    private javax.swing.JRadioButton introalpha;
    private javax.swing.JRadioButton intronum;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton startbutton;
    // End of variables declaration//GEN-END:variables

}
