/*
 * Test.java
 *
 * Created on September 16, 2008, 10:46 PM
 */

package ashw;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JTextField;


public class Test extends javax.swing.JFrame {
 JTextField[] jtf=new JTextField[26];
 String allCaps="ABCDEFGHIJKLMNOPQRSTUVWXYZ";

    /** Creates new form Test */
    public Test() {
        initComponents();
       Font myfont= new Font("Sans Serif",Font.BOLD, 14);
        for(int i=0;i<=25;i++){
          jtf[i]=new JTextField(5);
          jtf[i].setFont(myfont);
          jtf[i].setForeground(Color.black);
         /* int green = (int)(Math.random()*255);
         jtf[i].setBackground(new Color(green));*/

          jPanel1.add(jtf[i]);
   
          String s=String.valueOf(allCaps.charAt(i));
          jtf[i].setText(s);
          int in=(int)(Math.random()*i);
          jtf[in].setEnabled(true); 
         
          jtf[i].setEnabled(false);
         
         }
       
           
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        check = new javax.swing.JButton();
        alphalabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        check.setText("CHECK");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });

        alphalabel.setBackground(new java.awt.Color(255, 255, 255));
        alphalabel.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("OWN  STUDY");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 255));
        jLabel2.setText("*  Fill the blanks with coreect alphabet");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 0, 255));
        jLabel3.setText("Check the correct word");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(check)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(alphalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(170, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel2)
                .addContainerGap(106, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(check)
                    .addComponent(alphalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed

 String a=jtf[0].getText();
 if(a.equals("A"))   
 {
     alphalabel.setText("Correct Alphabet");
 }
else{
     alphalabel.setText("Wrong Alphabet");    
}

String b=jtf[1].getText();
 if(b.equals("B")){
     alphalabel.setText("Correct Alphabet");
 }
else{
    alphalabel.setText("Wrong Alphabet");
}

String c=jtf[2].getText();
if(c.equals("C")){
    alphalabel.setText("Correct Alphabet");
}
else{
    alphalabel.setText("Wrong Alphabet");
}

/*String d=jtf[3].getText();
if(d.equals("D")){
    alphalabel.setText("Correct Alphabet");
}
else{
    alphalabel.setText("Wrong Alphabet");
}

String e=jtf[4].getText();
if(e.equals("E")){
    alphalabel.setText("Correct Alphabet");
}
else{
    alphalabel.setText("Wrong Alphabet");
}

String f=jtf[5].getText();
if(f.equals("F")){
    alphalabel.setText("Correct Alphabet");
}
else{
    alphalabel.setText("Wrong Alphabet");
}
String g=jtf[6].getText();
if(g.equals("G")){
    alphalabel.setText("Correct Alphabet");
}
else{
    alphalabel.setText("Wrong Alphabet");
}*/


    
    // TODO add your handling code here:
}//GEN-LAST:event_checkActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel alphalabel;
    private javax.swing.JButton check;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
