/*
 * IntroToNum.java
 *
 * Created on August 11, 2008, 2:04 AM
 */

package ashwini;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author  Preeti
 */
public class IntroToNum extends javax.swing.JFrame {

    /** Creates new form IntroToNum */
    public IntroToNum() {
        initComponents();
    
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        ten = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        numlabel = new javax.swing.JLabel();
        imagelabel = new javax.swing.JLabel();
        wordlabel = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14));
        jLabel1.setForeground(new java.awt.Color(255, 51, 0));
        jLabel1.setText("Start Learning for Numbers");

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14));
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("* Click any of the following button for Number");

        one.setBackground(new java.awt.Color(51, 255, 0));
        one.setFont(new java.awt.Font("Tahoma", 1, 11));
        one.setText("1");
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });

        two.setBackground(new java.awt.Color(102, 255, 0));
        two.setFont(new java.awt.Font("Tahoma", 1, 11));
        two.setText("2");
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });

        three.setBackground(new java.awt.Color(102, 255, 51));
        three.setFont(new java.awt.Font("Tahoma", 1, 11));
        three.setText("3");
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });

        four.setBackground(new java.awt.Color(102, 255, 51));
        four.setFont(new java.awt.Font("Tahoma", 1, 11));
        four.setText("4");
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });

        five.setBackground(new java.awt.Color(102, 255, 51));
        five.setFont(new java.awt.Font("Tahoma", 1, 11));
        five.setText("5");
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });

        six.setBackground(new java.awt.Color(51, 255, 51));
        six.setFont(new java.awt.Font("Tahoma", 1, 11));
        six.setText("6");
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });

        seven.setBackground(new java.awt.Color(51, 255, 51));
        seven.setFont(new java.awt.Font("Tahoma", 1, 11));
        seven.setText("7");
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });

        eight.setBackground(new java.awt.Color(51, 255, 51));
        eight.setFont(new java.awt.Font("Tahoma", 1, 11));
        eight.setText("8");
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });

        nine.setBackground(new java.awt.Color(102, 255, 51));
        nine.setFont(new java.awt.Font("Tahoma", 1, 11));
        nine.setText("9");
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });

        ten.setBackground(new java.awt.Color(51, 255, 51));
        ten.setFont(new java.awt.Font("Tahoma", 1, 11));
        ten.setText("10");
        ten.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tenActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(51, 255, 0));
        jButton21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton21.setForeground(new java.awt.Color(255, 0, 102));
        jButton21.setText("ABC");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(one)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(two)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(three, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(four, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(five, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(six)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seven, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eight, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nine, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ten)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(four)
                    .addComponent(five)
                    .addComponent(six)
                    .addComponent(eight)
                    .addComponent(ten)
                    .addComponent(jButton21)
                    .addComponent(one)
                    .addComponent(two)
                    .addComponent(three)
                    .addComponent(nine)
                    .addComponent(seven))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        jButton11.setBackground(new java.awt.Color(102, 255, 51));
        jButton11.setText("1");

        jButton12.setBackground(new java.awt.Color(102, 255, 51));
        jButton12.setText("2");

        jButton13.setBackground(new java.awt.Color(102, 255, 51));
        jButton13.setText("3");

        jButton14.setBackground(new java.awt.Color(102, 255, 51));
        jButton14.setText("4");

        jButton15.setBackground(new java.awt.Color(102, 255, 51));
        jButton15.setText("5");

        jButton16.setBackground(new java.awt.Color(102, 255, 51));
        jButton16.setText("6");

        jButton17.setBackground(new java.awt.Color(102, 255, 51));
        jButton17.setText("7");

        jButton18.setBackground(new java.awt.Color(102, 255, 51));
        jButton18.setText("8");

        jButton19.setBackground(new java.awt.Color(51, 255, 51));
        jButton19.setText("9");

        jButton20.setBackground(new java.awt.Color(102, 255, 0));
        jButton20.setText("100");

        numlabel.setBackground(new java.awt.Color(255, 255, 255));
        numlabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 48)); // NOI18N
        numlabel.setOpaque(true);

        imagelabel.setBackground(new java.awt.Color(255, 255, 255));
        imagelabel.setOpaque(true);

        wordlabel.setBackground(new java.awt.Color(0, 0, 255));
        wordlabel.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        wordlabel.setForeground(new java.awt.Color(255, 0, 0));
        wordlabel.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(numlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wordlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(imagelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton14)
                        .addComponent(jButton15)
                        .addComponent(jButton16)
                        .addComponent(jButton17)
                        .addComponent(jButton18)
                        .addComponent(jButton19)
                        .addComponent(jButton20)
                        .addComponent(jButton13)
                        .addComponent(jButton12)
                        .addComponent(jButton11)))
                .addContainerGap())
        );

        back.setBackground(new java.awt.Color(153, 51, 255));
        back.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14));
        back.setText("BACK");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jButton24.setBackground(new java.awt.Color(153, 0, 204));
        jButton24.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14));
        jButton24.setText("SPEECH");

        exit.setBackground(new java.awt.Color(153, 0, 255));
        exit.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 14));
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jButton24)
                        .addGap(29, 29, 29)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(jButton24)
                    .addComponent(exit))
                .addGap(69, 69, 69))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
ImageIcon ic1 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\one.jpeg");
ImageIcon ic2=new ImageIcon("D:\\Ash\\PROJECT\\images\\one ball.jpeg");
wordlabel.setText("         One   ");
Image image1=ic1.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image2=ic2.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon1=new ImageIcon(image1);
ImageIcon icon2=new ImageIcon(image2);
numlabel.setIcon(icon1);
imagelabel.setIcon(icon2);
    // TODO add your handling code here:
}//GEN-LAST:event_oneActionPerformed

private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
ImageIcon ic3 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\two.jpeg");
ImageIcon ic4=new ImageIcon("D:\\Ash\\PROJECT\\images\\two ball.jpeg");
wordlabel.setText("         Two   ");
Image image3=ic3.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image4=ic4.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon3=new ImageIcon(image3);
ImageIcon icon4=new ImageIcon(image4);
numlabel.setIcon(icon3);
imagelabel.setIcon(icon4);
    // TODO add your handling code here:
}//GEN-LAST:event_twoActionPerformed

private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
ImageIcon ic9 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\five.jpeg");
ImageIcon ic10=new ImageIcon("D:\\Ash\\PROJECT\\images\\five balls.jpeg");
wordlabel.setText("         Five   ");
Image image9=ic9.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image10=ic10.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon9=new ImageIcon(image9);
ImageIcon icon10=new ImageIcon(image10);
numlabel.setIcon(icon9);
imagelabel.setIcon(icon10);
    
    // TODO add your handling code here:
}//GEN-LAST:event_fiveActionPerformed

private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
ImageIcon ic5 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\three.jpeg");
ImageIcon ic6=new ImageIcon("D:\\Ash\\PROJECT\\images\\three ball.jpeg");
wordlabel.setText("         Three   ");
Image image5=ic5.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image6=ic6.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon5=new ImageIcon(image5);
ImageIcon icon6=new ImageIcon(image6);
numlabel.setIcon(icon5);
imagelabel.setIcon(icon6);
    
    // TODO add your handling code here:
}//GEN-LAST:event_threeActionPerformed

private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
ImageIcon ic7 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\four.jpeg");
ImageIcon ic8=new ImageIcon("D:\\Ash\\PROJECT\\images\\four ice-cream.jpeg");
wordlabel.setText("         Four   ");
Image image7=ic7.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image8=ic8.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon7=new ImageIcon(image7);
ImageIcon icon8=new ImageIcon(image8);
numlabel.setIcon(icon7);
imagelabel.setIcon(icon8);
    
    // TODO add your handling code here:
}//GEN-LAST:event_fourActionPerformed

private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
ImageIcon ic11 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\six.jpeg");
ImageIcon ic12=new ImageIcon("D:\\Ash\\PROJECT\\images\\six balls.jpeg");
wordlabel.setText("         Six   ");
Image image11=ic11.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image12=ic12.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);

ImageIcon icon11=new ImageIcon(image11);
ImageIcon icon12=new ImageIcon(image12);
numlabel.setIcon(icon11);
imagelabel.setIcon(icon12);
    
    // TODO add your handling code here:
}//GEN-LAST:event_sixActionPerformed

private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
ImageIcon ic13 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\seven.jpeg");
ImageIcon ic14=new ImageIcon("D:\\Ash\\PROJECT\\images\\seven balls.jpeg");
wordlabel.setText("         Seven   ");
Image image13=ic13.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image14=ic14.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon13=new ImageIcon(image13);
ImageIcon icon14=new ImageIcon(image14);
numlabel.setIcon(icon13);
imagelabel.setIcon(icon14);
    // TODO add your handling code here:
}//GEN-LAST:event_sevenActionPerformed

private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed

ImageIcon ic15 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\eight.jpeg");
ImageIcon ic16=new ImageIcon("D:\\Ash\\PROJECT\\images\\eight balls.jpeg");
wordlabel.setText("         Eight   ");
Image image15=ic15.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image16=ic16.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon15=new ImageIcon(image15);
ImageIcon icon16=new ImageIcon(image16);
numlabel.setIcon(icon15);
imagelabel.setIcon(icon16);
    // TODO add your handling code here:
}//GEN-LAST:event_eightActionPerformed

private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed

ImageIcon ic17 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\nine.jpeg");
ImageIcon ic18=new ImageIcon("D:\\Ash\\PROJECT\\images\\nine balls.jpeg");
wordlabel.setText("         Nine   ");
Image image17=ic17.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image18=ic18.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon17=new ImageIcon(image17);
ImageIcon icon18=new ImageIcon(image18);
numlabel.setIcon(icon17);
imagelabel.setIcon(icon18);
    // TODO add your handling code here:
}//GEN-LAST:event_nineActionPerformed

private void tenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tenActionPerformed

    ImageIcon ic19 =new ImageIcon("D:\\Ash\\PROJECT\\images\\Letter\\ten.jpeg");
ImageIcon ic20=new ImageIcon("D:\\Ash\\PROJECT\\images\\ten balls.jpeg");
wordlabel.setText("         Ten   ");
Image image19=ic19.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
Image image20=ic20.getImage().getScaledInstance(imagelabel.getWidth(),imagelabel.getHeight(),Image.SCALE_AREA_AVERAGING);
ImageIcon icon19=new ImageIcon(image19);
ImageIcon icon20=new ImageIcon(image20);
numlabel.setIcon(icon19);
imagelabel.setIcon(icon20);
    // TODO add your handling code here:
}//GEN-LAST:event_tenActionPerformed

private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed

    setVisible(false);
    new IntroToAlphas().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_jButton21ActionPerformed

private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
    setVisible(false);
    new Learning().setVisible(true);
    // TODO add your handling code here:
}//GEN-LAST:event_backActionPerformed

private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);
    // TODO add your handling code here:
}//GEN-LAST:event_exitActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IntroToNum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton eight;
    private javax.swing.JButton exit;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JLabel imagelabel;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton24;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton nine;
    private javax.swing.JLabel numlabel;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton ten;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JLabel wordlabel;
    // End of variables declaration//GEN-END:variables

}
